name: update playlist
on:
  schedule:
    - cron:  '30 * * * *'

env:
  REGISTRY: ghcr.io

jobs:
  update_playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      
      - run: echo ${{ secrets.JEFF_CONFIG_INI }} | base64 -d > config.ini && grep station_codes config.ini && python run.py
        env:
          JEFF_CONFIG_INI: ${{ secrets.JEFF_CONFIG_INI }}
